url: http://codeveyor.com
baseurl: ""

# Site settings
title: Codeveyor
email: codeveyor@gmail.com
description: "You was never so close to implementation of your business ideas before

Believe or not, Codeveyor is not just one more outsourcing company. Our mission - is to have a joy to improve ourselves and our projects continuously in every possible way. We don't hire people to do their work. We are hiring passionate tech maniacs to create decisions, that will drive industry forward.

Our main goal is to help grow up ideas and talents. To cherish carefully crafted tech family atmosphere, to have a possibility to attract more right people to our processes. We are not saving on staff, and staff is not saving on quality of products we made. Let's make your business together, and you will see that it is a difference in how your desires will built."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Chuck Norris
  pic: 1
  position: Resolving Issues Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Alex Golub
  pic: 2
  position: Founder, Acting Team Lead, iOS developer
  social:
    - title: twitter
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Victoria Arnautu
  pic: 3
  position: Head HR Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/codeveyor
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/users/1236726/alex
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/Codeveyor

# Postal address (add as many lines as necessary)
address:
  - line: Kyiv, Ukraine

# Build settings
markdown: kramdown
permalink: pretty